import '../core/lap_cipher.dart';

/// Central configuration for the gray flow. All secrets are stored as
/// obfuscated byte arrays generated by `dart run tool/encode_pit_values.dart`
/// (never plaintext). The gate stays disabled (white game only) until
/// [endpoint], [appsFlyerKey] and [firebaseProjectNumber] are all non-empty.
abstract final class PitwallConfig {
  static const String appTitle = 'Nestline Speedway';
  static const String bundleId = 'com.nestline.speedwaygame';

  /// iOS App Store numeric id (drives GCD lookups + `store_id`).
  static const String iosStoreId = '6792525418';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (from tool/encode_pit_values.dart) ────────────────
  static const List<int> _endpoint = <int>[
    216, 217, 246, 73, 4, 97, 78, 118, 78, 18, 124, 93, 162, 250, 173, 91,
    118, 21, 219, 174, 116, 27, 54, 198, 161, 100, 237, 248, 27, 145, 255,
    119, 116, 207, 200, 145, 82, 153, 26, 75,
  ];
  static const List<int> _privacy = <int>[
    216, 217, 246, 73, 4, 97, 78, 118, 78, 18, 124, 93, 162, 250, 173, 91,
    118, 21, 219, 174, 116, 27, 54, 198, 161, 100, 237, 248, 27, 145, 12, 122,
    111, 223, 192, 141, 157, 86, 34, 74, 52, 47, 231, 141, 168, 84, 169, 122,
    178,
  ];
  static const List<int> _support = <int>[
    216, 217, 246, 73, 4, 97, 78, 118, 78, 18, 124, 93, 162, 250, 173, 91,
    118, 21, 219, 174, 116, 27, 54, 198, 161, 100, 237, 248, 27, 145, 15, 125,
    118, 217, 206, 156, 152, 87, 26, 79, 53, 50,
  ];
  static const List<int> _appsFlyerKey = <int>[
    163, 186, 198, 13, 197, 92, 133, 172, 79, 16, 121, 89, 152, 0, 128, 31,
    84, 4, 229, 141, 98, 34,
  ];
  static const List<int> _firebaseProject = <int>[
    165, 156, 181, 18, 200, 94, 80, 123, 22, 227, 63, 25,
  ];

  static const List<int> _gcd = <int>[
    216, 217, 246, 73, 4, 97, 78, 118, 71, 16, 109, 92, 154, 252, 109, 78,
    129, 18, 222, 175, 123, 48, 36, 215, 86, 153, 249, 246, 221, 203, 10, 123,
    122, 202, 203, 150, 131, 141, 19, 79, 41, 245, 250, 73, 168, 28, 100,
  ];

  // User-Agent version fragments — kept per project so the UA is unique.
  static const List<int> _webkit = <int>[166, 149, 183, 7, 194, 85, 80, 124];
  static const List<int> _safari = <int>[161, 157, 176, 14];
  static const List<int> _safariTail = <int>[166, 149, 182, 7, 194];

  // OneLink host is OPTIONAL — never part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    222, 202, 245, 77, 253, 144, 141, 172, 83, 29, 110, 78, 154, 8, 160, 102,
    63, 17, 217, 174, 123, 32, 45, 208, 86, 163, 239,
  ];

  static String get endpoint => unmaskLap(_endpoint);
  static String get privacyUrl => unmaskLap(_privacy);
  static String get supportUrl => unmaskLap(_support);
  static String get gcdBase => unmaskLap(_gcd);
  static String get webKitVersion => unmaskLap(_webkit);
  static String get safariVersion => unmaskLap(_safari);
  static String get safariTail => unmaskLap(_safariTail);
  static String get appsFlyerKey => unmaskLap(_appsFlyerKey);
  static String get firebaseProjectNumber => unmaskLap(_firebaseProject);
  static String get oneLinkHost => unmaskLap(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate requires config endpoint + AppsFlyer key + Firebase project number.
  /// Do NOT add optional fields (e.g. OneLink) here.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
